[package]
name = "lycaon"
version = "0.1.0"
authors = ["Hamish Hutchings <moredhel@aoeu.me>"]

[dependencies]
# pinned
ring = "0.11.0" # cookie depends on this version
# cookie = "0.10"

rocket = "0.3.5"
rocket_codegen = "0.3.5"
rocket_contrib = "0.3.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
uuid = { version = "0.5.1", features = ["v4", "rustc-serialize"] }
log = "0.3"
env_logger = "0.4.3"
fern = "0.4"
chrono = "0.4.0"
ctrlc = { version = "3.0", features = ["termination"] }
hostname = "^0.1"

protobuf = "1.4.2"
grpcio = "0.1.2"
config = "0.7.0"
args = "2.0"
getopts = "0.2.15"

futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"

orset = "0.2.0"

# failure = { git = 'https://github.com/withoutboats/failure', rev = "ae276f58615174e5b2dbba8dd7c6e47a033c7e2c"}
failure = "0.1"
failure_derive = "0.1"

lycaon-protobuf = { path = "./lib/protobuf" }
lycaon-backend = { path = "./lib/backend" }
lycaon-errors = { path = "./lib/errors" }

[build-dependencies]

[dev-dependencies]
quickcheck = "0.4"
quickcheck_macros = "0.4"
